; ============================================================
; PlatformIO Project Configuration
; Sistema de Monitoreo de Nivel de Tanque
; Placa: ESP32-S3 DevKitC-1 (N16R8)
; ============================================================
[env:esp32-s3-devkitc-1]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino

; Velocidad del monitor serial
monitor_speed = 115200

; Librerías necesarias (ninguna externa, todo con Arduino core)
lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0

; Opciones de compilación útiles para debugging
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -D ARDUINO_USB_CDC_ON_BOOT=1
